version: '3.9'

services:
  menu-mono-db:
    image: postgres:13.5
    container_name: menu-mono-db
    restart: always
    networks:
      - menu-mono-net
    ports:
      - '5433:5432'
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

  menu-mono-db-test:
    image: postgres:13.5
    restart: always
    container_name: menu-mono-testdb
    ports:
      - '5434:5432'
    env_file:
      - .env.test
    volumes:
      - postgres-test:/var/lib/postgresql/data

volumes:
  postgres:
    name: menu-mono-db
  postgres-test:
    name: menu-mono-testdb

networks:
  menu-mono-net:
    driver: bridge
