version: '3.8'
services:
  postgres:
    image: postgres:13.5
    container_name: postgres
    # restart: always
    networks:
      - menu-mono-net
    ports:
      - '5433:5432'
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: menu-mono-db

networks:
  menu-mono-net:
    driver: bridge
