version: '3.8'
services:
  menu-prisma-migrate:
    container_name: menu-prisma-migrate
    build:
      context: prisma
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - menu-mono-net
    depends_on:
      - postgres

  postgres:
    image: postgres:13.5
    container_name: postgres
    # restart: always
    networks:
      - menu-mono-net
    ports:
      - '5433:5432'
    env_file:
      - .env.docker
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: menu-mono-db

networks:
  menu-mono-net:
    driver: bridge
